package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Almos.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Almos extends Panda {
	public void Action(Fotel f) {
		if (getHand1() != null)
		{
			release();
			move(f);
		}
	}
}
