package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Breakable.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Breakable extends Field {
	private int remainLifetime;


	public void stepped(Unit u) {
		if (u!= null)
		{
			remainLifetime--;
			if (remainLifetime<1)
			{
				u.die();
			}
		}
	}
}
