package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entry.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Entry extends Field {
	private Control entryField;
}
