package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Exit.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Exit extends Field {
	public void stepped(Orangutan o) {
	    if (o != null) {
            o.exit();
        }
	}

    public void setContain(Unit contain) {
        this.stepped(contain);
    }
}
