package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Fotel.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Fotel extends Field {//ez a szekvencia is szar volt *clap clap* kezdem unni
	public void Update() {
		if (getContain()==null)
		{
			for (Field field : getNei()) {
				if (field.getContain()!=null)
				{
					field.getContain().action(this);
				}
			}
		}
	}
}
