package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jatek.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Jatek extends Field {
	public void Update() {
		for (Field field : getNei()) {
			if (field.getContain()!=null)
			{
				field.getContain().action(this);
			}
		}
		if (getContain() != null)
		{
			getContain().action(this);
		}
	}
}
