package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ugralos.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Ugralos extends Panda {
	public void Action(Csoki cs) {
		move(cs);
	}
}
