package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Action.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public interface Action {
	public void action(Csoki cs);
	
	public void action(Jatek j);
	
	public void action(Fotel f);
}
