//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Control.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Control {
	private int numOfPlayers;
	public void init() {
	}
	
	public void move(Unit u, Field f) {
	}
	
	public void Start() {
	}
	
	public void End() {
	}
}
