//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Field {
	private Control map;
	private Unit place;
	private Unit place:Field*;
	private Unit fieldOn;
	private Field nei;
	public void Update() {
	}
	
	public void stepped(Unit u) {
	}
}
