package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//


import java.util.ArrayList;

public class Field {
	private Control map;
	private Unit contain;
	private ArrayList<Field> nei;
	public void Update() {
	}
	
	public void stepped(Unit u) {
	}

	public Control getMap() {
		return map;
	}

	public void setMap(Control map) {
		this.map = map;
	}

	public Unit getFieldOn() {
		return contain;
	}

	public void setFieldOn(Unit fieldOn) {
		this.contain = fieldOn;
	}

	public ArrayList<Field> getNei() {
		return nei;
	}

	public void setNei(ArrayList<Field> nei) {
		this.nei = nei;
	}
}
