package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Fotel.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Fotel extends Field {
	public void Update() {
	}
}
