//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ijedos.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Ijedos extends Panda {
	public void Action(Jatek j) {
	}
}
