//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jatek.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Jatek extends Field {
	public void Update() {
	}
}
