//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Panda.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Panda extends Unit {
	private Control pandas;
	public void grab(Unit u) {
	}
	
	public void exit() {
	}
	
	public void die() {
	}
}
