package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Player {
	private int points;
	private Orangutan myOran;

	private void givePoints(int i) {
		points += i;
	}

	public int getPoints() {
		return points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	public Orangutan getMyOran() {
		return myOran;
	}

	public void setMyOran(Orangutan myOran) {
		this.myOran = myOran;
	}


}
