//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Player {
	private int points;
	private Orangutan myOran;
	private Control player;
	private viod givePoints(int i) {
	}
}
