package com.company;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Szekreny.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public class Szekreny extends Field {
	private Szekreny szekrenypar;
	public void stepped(Orangutan o) {
	}
	
	public void stepped(Panda p) {
	}
}
