//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Unit.java
//  @ Date : 2019. 03. 22.
//  @ Author : 
//
//




public abstract class Unit implements Action {
	private Field contain:Unit*;
	private Field contain;
	private Field contain;
	private Unit hand1;
	private Unit hand2;
	public void move(Field f) {
	}
	
	public void grab(Unit u) {
	}
	
	public void exit() {
	}
	
	public void die() {
	}
	
	public void release(unit u) {
	}
}
